[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "detect-wildlife-crossings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "albumentations>=2.0.8",
    "centerline>=1.1.1",
    "contextily>=1.6.2",
    "dask>=2025.11.0",
    "fiona>=1.10.1",
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "ipykernel>=7.0.1",
    "ipympl>=0.9.8",
    "libpysal>=4.13.0",
    "mapclassify>=2.10.0",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "opencv-python>=4.12.0.88",
    "overpass>=0.7.2",
    "owslib>=0.34.1",
    "plotly>=6.3.1",
    "pyarrow>=22.0.0",
    "pygeoutils>=0.19.5",
    "pyproj>=3.7.2",
    "rasterio>=1.4.3",
    "scikit-image>=0.25.2",
    "shapely>=2.1.2",
    "skeletor>=1.3.0",
    "supervision>=0.26.1",
    "tqdm>=4.67.1",
    "ultralytics<=8.3.40",
    "wandb>=0.22.2",
]


[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[tool.uv.sources]
detect-wildlife-crossings = { workspace = true }

[dependency-groups]
dev = ["detect-wildlife-crossings"]

[tool.ruff]
extend-include = ["*.ipynb"]
