_wandb:
    value:
        cli_version: 0.22.2
        e:
            kxil9grsb99tk684nvdxgzxnxqiomd5n:
                codePath: notebooks\train-yolo-model.ipynb
                codePathLocal: train-yolo-model.ipynb
                email: raffael.schreiber@gmail.com
                executable: c:\code\cassda-zertifikatsarbeit\.venv\Scripts\python.exe
                git:
                    commit: 98c3e31e4b06ee44cbc54cbededa1ae8b542be76
                    remote: https://github.com/rschre/cassda-zertifikatsarbeit.git
                host: DESKTOP-52CNESF
                os: Windows-11-10.0.26100-SP0
                program: c:\code\cassda-zertifikatsarbeit\notebooks\train-yolo-model.ipynb
                python: CPython 3.13.1
                root: c:\code\cassda-zertifikatsarbeit\notebooks
                startedAt: "2025-10-24T13:51:46.799602Z"
                writerId: kxil9grsb99tk684nvdxgzxnxqiomd5n
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 41
                - 80
            "2":
                - 1
                - 41
                - 80
            "3":
                - 2
                - 13
            "4": 3.13.1
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
